version: '3'

services:
  sql-db:
    image: mariadb:10.11.3
    environment:
      MYSQL_ROOT_PASSWORD: mariadb_root_password
      MYSQL_DATABASE: globant_migration
      MYSQL_USER: mariadb_user
      MYSQL_PASSWORD: mariadb_password
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  data: